// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var chapterResponse = ChapterResponse.FromJson(jsonString);

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

public class ChapterResponse
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("timestamp")]
    public long Timestamp { get; set; }

    [JsonProperty("hash")]
    public string Hash { get; set; }

    [JsonProperty("volume")]
    public string Volume { get; set; }

    [JsonProperty("chapter")]
    public string Chapter { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("lang_name")]
    public string LangName { get; set; }

    [JsonProperty("lang_code")]
    public string LangCode { get; set; }

    [JsonProperty("manga_id")]
    public long MangaId { get; set; }

    [JsonProperty("group_id")]
    public long GroupId { get; set; }

    [JsonProperty("group_id_2")]
    public long GroupId2 { get; set; }

    [JsonProperty("group_id_3")]
    public long GroupId3 { get; set; }

    [JsonProperty("comments")]
    public object Comments { get; set; }

    [JsonProperty("server")]
    public Uri Server { get; set; }

    [JsonProperty("page_array")]
    public List<string> PageArray { get; set; }

    [JsonProperty("long_strip")]
    public long LongStrip { get; set; }

    [JsonProperty("status")]
    public string Status { get; set; }

    public static ChapterResponse FromJson(string json) => JsonConvert.DeserializeObject<ChapterResponse>(json);
}
