// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mangaResponse = MangaResponse.FromJson(jsonString);

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

public class MangaResponse
{
    [JsonProperty("manga")]
    public Manga Manga { get; set; }

    [JsonProperty("chapter")]
    public Dictionary<string, Chapter> Chapters { get; set; }
    public static MangaResponse FromJson(string json) => JsonConvert.DeserializeObject<MangaResponse>(json);

}

public class Chapter
{
    [JsonProperty("volume")]
    public string Volume { get; set; }

    [JsonProperty("chapter")]
    public string ChapterNo { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("lang_code")]
    public string LangCode { get; set; }

    [JsonProperty("group_id")]
    public long GroupId { get; set; }

    [JsonProperty("group_name")]
    public string GroupName { get; set; }

    [JsonProperty("group_id_2")]
    public long GroupId2 { get; set; }

    [JsonProperty("group_name_2")]
    public object GroupName2 { get; set; }

    [JsonProperty("group_id_3")]
    public long GroupId3 { get; set; }

    [JsonProperty("group_name_3")]
    public object GroupName3 { get; set; }

    [JsonProperty("timestamp")]
    public long Timestamp { get; set; }
}

public class Manga
{
    [JsonProperty("cover_url")]
    public string CoverUrl { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("title")]
    public string Title { get; set; }

    [JsonProperty("artist")]
    public string Artist { get; set; }

    [JsonProperty("author")]
    public string Author { get; set; }

    [JsonProperty("status")]
    public long Status { get; set; }

    [JsonProperty("genres")]
    public List<long> Genres { get; set; }

    [JsonProperty("last_chapter")]
    public string LastChapter { get; set; }

    [JsonProperty("lang_name")]
    public string LangName { get; set; }

    [JsonProperty("lang_flag")]
    public string LangFlag { get; set; }

    [JsonProperty("hentai")]
    public long Hentai { get; set; }

    [JsonProperty("links")]
    public Links Links { get; set; }
    
}

public class Links
{
    [JsonProperty("ap")]
    public string Ap { get; set; }

    [JsonProperty("mu")]
    public string Mu { get; set; }

    [JsonProperty("raw")]
    public Uri Raw { get; set; }
}
